---
# tasks file for vault-server
- name: Install Local HashiCorp Repo
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Repository
    baseurl: "{{ repo_server }}/{{ repo_path }}"
    gpgcheck: true
    gpgkey: "{{ repo_server }}/{{ cert_path }}"
    enabled: true
    state: present
  when: not connected_network
- name: Add the Internet HashiCorp Repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: true
    enabled: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  when: connected_network
- name: Install HashiCorp Vault 
  ansible.builtin.dnf:
    name: vault 
    state: present
  when: "ansible_facts['distribution_major_version'] >= \"8\""
- name: Install HashiCorp Vault 
  ansible.builtin.yum:
    name: vault 
    state: present
  when: "ansible_facts['distribution_major_version'] <= \"7\""
- name: Enable HashiCorp Vault on Startup
  ansible.builtin.service:
    name: vault
    enabled: true
    state: started
  when: enable_service
