---
# - name: "Prepare the {{ ansible_facts['distribution'] }} guest operating system."
#   include_tasks: "{{ ansible_facts['distribution'] | lower }}.yml"
#   when: "ansible_facts['distribution'] == 'Ubuntu'"
- name: "Prepare the {{ ansible_facts['distribution'] }} guest operating system."
  include_tasks: redhat.yml
  when: "ansible_facts['distribution'] in ['RedHat', 'CentOS', 'Rocky', 'AlmaLinux', 'OracleLinux']"
# - name: "Prepare the {{ ansible_facts['os_family'] }} guest operating system."
#   ansible.builtin.include_tasks: windows.yml
#   when: ansible_facts['os_family'] == 'Windows'
