---
# tasks file for vault-server
- name: Install HashiCorp Repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Repository
    baseurl: '{{ hashicorp_rpm_repo_url }}'
    gpgcheck: true
    gpgkey: '{{ hashicorp_gpg_key_url }}'
    enabled: true
    state: present
- name: Install HashiCorp Vault 
  ansible.builtin.dnf:
    name: vault 
    state: present
    validate_certs: '{{ trust_repository_certs }}'
  when: "ansible_facts['distribution_major_version'] >= \"8\""
- name: Install HashiCorp Vault 
  ansible.builtin.yum:
    name: vault 
    state: present
    validate_certs: '{{ trust_repository_certs }}'
  when: "ansible_facts['distribution_major_version'] <= \"7\""
- name: Copy Vault Config
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    backup: true
    owner: vault
    group: vault
    mode: '0644'
  when:
    - enable_tls
- name: Copy No TLS Vault Config
  ansible.builtin.template:
    src: vault.hcl-notls.j2
    dest: /etc/vault.d/vault.hcl
    backup: true
    owner: vault
    group: vault
    mode: '0644'
  when:
    - not enable_tls
- name: Adjust Host Firewall to Allow Vault Services
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 8200/tcp
    - 8201/tcp
- name: Configure Vault Service Startup
  ansible.builtin.service:
    name: vault
    enabled: '{{ enable_service }}'
    state: '{{ service_state }}'
